#!/bin/bash
# Usage: ./run_CVRP class name max_trials runs [ optimum ]

if [ -z "$3" ]; then
    echo "./run_CVRP class name max_trials runs [ optimum ]"
    exit
fi

lkh="./LKH"
class=$1
name=$2
max_trials=$3
runs=$4
optimum=$5
par=TMP/$name.pid$$.par

mkdir -p TOURS
mkdir -p TOURS/$class
mkdir -p TMP
# mkdir -p SOLUTIONS
# mkdir -p SOLUTIONS/$class
mkdir -p TMP
mkdir -p PI_FILES
mkdir -p PI_FILES/$class

echo "SPECIAL" > $par
echo "PROBLEM_FILE = INSTANCES/$class/$name.vrp" >> $par
arr=(${name//-k/ })
salesmen=${arr[1]}
if [ -n "$salesmen" ]; then
    echo "SALESMEN = $salesmen" >> $par
fi

echo "MAX_TRIALS = $max_trials" >> $par
echo "RUNS = $runs" >> $par
echo "INITIAL_PERIOD = 1000" >> $par
echo "INITIAL_TOUR_ALGORITHM = CVRP" >> $par
# echo "PI_FILE = PI_FILES/$class/$name.pi" >> $par
# echo "CANDIDATE_SET_TYPE = QUADRANT" >> $par
# echo "CANDIDATE_FILE = $name.cand" >> $par

if false; then
    for FILE in `ls TOURS/$class/$name.*.tour | sort -n -t . -k3,4` ;
    do
        echo "INITIAL_TOUR_FILE = $FILE" >> $par
        break
    done
fi

if false; then
    max_merge_tours=10
    merge_tours=0
    for FILE in `ls TOURS/$class/$name.*.tour | sort -n -t . -k2,3` ;
    do
         let "merge_tours++"
         if [ $merge_tours -gt $max_merge_tours ]; then
             break
         fi
         echo "MERGE_TOUR_FILE = $FILE" >> $par
    done
    echo "MAX_CANDIDATES = 0" >> $par
fi

# echo "TOUR_FILE = TOURS/$class/$name.$.tour" >> $par
# echo "SINTEF_SOLUTION_FILE = SOLUTIONS/$class/$name.$.sol" >> $par

if [ -n "$optimum" ]; then
    echo "OPTIMUM = $optimum" >> $par
fi

echo "SEED = 0" >> $par
echo "TRACE_LEVEL = 1" >> $par

$lkh $par

/bin/rm -f $par
